# Generated by Django 6.0.5 on 2026-06-03 12:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="The title of the book", max_length=255),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, default="Unknown Author", max_length=255
                    ),
                ),
                (
                    "cover_url",
                    models.URLField(
                        help_text="Direct link to a book cover image", max_length=500
                    ),
                ),
                ("category", models.CharField(default="General", max_length=100)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.5,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("pages", models.PositiveIntegerField(default=200)),
                (
                    "ratings_count",
                    models.CharField(
                        default="0",
                        help_text="Formatted ratings (e.g. 1,240)",
                        max_length=50,
                    ),
                ),
                (
                    "reviews_count",
                    models.CharField(
                        default="0",
                        help_text="Formatted reviews (e.g. 320)",
                        max_length=50,
                    ),
                ),
                ("is_recommended", models.BooleanField(default=False)),
                (
                    "color_gradient",
                    models.CharField(
                        default="from-slate-700 to-slate-900",
                        help_text="Tailwind CSS gradient classes (e.g., from-emerald-800 to-teal-900)",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="books/files/"),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL if hosted outside storage",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        default="pdf",
                        help_text="e.g. pdf, epub, mobi, mp3",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="books.book",
                    ),
                ),
            ],
        ),
    ]
