# Generated by Django 6.0.5 on 2026-06-08 08:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AddField(
            model_name="bookfile",
            name="file_size_mb",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="color_gradient",
            field=models.CharField(
                default="from-slate-700 to-slate-900",
                help_text="Tailwind CSS gradient classes",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_url",
            field=models.URLField(
                blank=True,
                help_text="Fallback cover URL if no upload",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="ratings_count",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="book",
            name="reviews_count",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="bookfile",
            name="file",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload PDF, EPUB, or MOBI file",
                max_length=255,
                null=True,
                verbose_name="raw",
            ),
        ),
        migrations.AlterField(
            model_name="bookfile",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("epub", "EPUB"),
                    ("mobi", "MOBI"),
                    ("mp3", "Audiobook MP3"),
                ],
                default="pdf",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bookfile",
            name="file_url",
            field=models.URLField(
                blank=True, help_text="External URL fallback", max_length=500, null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bookfile",
            unique_together={("book", "file_format")},
        ),
    ]
